/*
 * generated by Xtext
 */
package eu.quanticol.carma.core.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class CARMAUiModule extends eu.quanticol.carma.core.ui.AbstractCARMAUiModule {
	public CARMAUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
