/*
 * generated by Xtext
 */
package eu.quanticol.carma.core.ui.contentassist

import eu.quanticol.carma.core.ui.contentassist.AbstractCARMAProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class CARMAProposalProvider extends AbstractCARMAProposalProvider {
}
