/*
 * generated by Xtext
 */
package eu.quanticol.carma.ui.wizard;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;


/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class CARMAExecutableExtensionFactoryWizard extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return ActivatorWizard.getDefault().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return ActivatorWizard.getDefault().getInjector();
	}
	
}
