/*
 * generated by Xtext
 */
package eu.quanticol.carma.core;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class CARMARuntimeModule extends eu.quanticol.carma.core.AbstractCARMARuntimeModule {

}
