/*
* generated by Xtext
*/
package eu.quanticol.carma.core;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class CARMAStandaloneSetup extends CARMAStandaloneSetupGenerated{

	public static void doSetup() {
		new CARMAStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

